### ISSUE TITLE
Refresh scrollbar after successful axios response?

### ISSUE THREAD

**Issue by rowild** [lecion/vue-perfect-scrollbar#18]
Currently, a news list is loading and actually even displayed, but the scrollbar is hidden. The template looks like this:

`
<VuePerfectScrollbar class="scroll-area" v-once :settings="settings" @ps-scroll-y="scrollHandle" v-if="newsList">
    <article v-for="(item, index) in newsList" :key="index" class="c-bg c-bg--shadow c-bg--hover c-bg--padding  c-list-txt--headers"> [...]`

'v-if="newsList"' is updated after an axios call. The entries are showing, but no scrolling of any kind (mousewheel, touch) is available:

Any idea what I have to do?

**Comment by romanran** [comment]
You have v-once in your code. Remove it and it will work

**Comment by lecion** [comment]
@rowild remove v-once and try again

**Comment by rowild** [comment]
@romanran sorry, I didn't see your answer  until today! So a late thank you for your feedback!
@lecion thank you for your feedback!
Since this was already quite a while ago and the app is working in the meantime, I guess this is what I did :-)
Thanks again and have a good day!

**Comment by lecion** [comment]
@rowild Sorry for my late response, have a good day :)
