### ISSUE TITLE
ps-y-reach-end triggers on load.

### ISSUE THREAD

**Issue by xeroxstar** [lecion/vue-perfect-scrollbar#20]
I am not sure why but when the app loads the ps-y-reach-end  triggers without scrolling it!!!

**Comment by AngularDevMrs** [comment]
I am seeing the same problem. Is there a reason for this?

**Comment by lecion** [comment]
@xeroxstar @AngularDevMrs  Pls try to the new version

**Comment by intermundos** [comment]
I see the same issue on load. 

```    "vue-perfect-scrollbar": "^0.2.1",```
