### ISSUE TITLE
How to change the scroll bar css

### ISSUE THREAD

**Issue by 1947324563** [lecion/vue-perfect-scrollbar#28]
如何改变滚动条样式
How to change the scroll bar css

**Comment by lecion** [comment]
Try to custom the class below:
Scrollbar rail styles
.ps__rail-x
.ps__rail-y
Scrollbar thumb styles
.ps__thumb-x
.ps__thumb-y
[https://github.com/mdbootstrap/perfect-scrollbar/blob/master/css/perfect-scrollbar.css](https://github.com/mdbootstrap/perfect-scrollbar/blob/master/css/perfect-scrollbar.css)
